Repository aws/aws-parallelcluster-ui, pull requests merged in 2023-04, with the labels that each got.

#164 Removed SSMDefaultUser substack
  infrastructure/README.md
  infrastructure/SSMSessionProfile-cfn.yaml
  infrastructure/parallelcluster-ui.yaml
  infrastructure/update-environment-infra.sh
  infrastructure/upload.sh
Labels: release:breaking-change, release:improvement

#173 Update Storage section layout
  frontend/src/old-pages/Configure/Storage.tsx
  frontend/src/old-pages/Configure/Storage/AddStorageForm.tsx
Labels: release:improvement

#176 Clear ProvisionedThroughput in EFS storage when corresponding checkbox is unchecked
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Storage.tsx
  frontend/src/old-pages/Configure/Storage/__tests__/validateEfs.test.ts
  frontend/src/old-pages/Configure/Storage/storage.validators.ts
Labels: release:bugfix

#188 Add create cluster loading flashbar
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Create.tsx
Labels: release:improvement
