Repository aws/aws-parallelcluster-ui, pull requests merged in 2023-02, with the labels that each got.

#52 Let the user specify a custom name for the shared storage
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Storage.tsx
  frontend/src/old-pages/Configure/Storage/__tests__/validateStorageName.test.ts
  frontend/src/old-pages/Configure/Storage/storage.validators.ts
Labels: release:feature

#53 Add possibility to select more than one storage at a time
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Storage.tsx
  frontend/src/old-pages/Configure/Storage.types.ts
  frontend/src/old-pages/Configure/Storage/AddStorageForm.tsx
  frontend/src/old-pages/Configure/Storage/__tests__/AddStorageForm.test.tsx
  frontend/src/old-pages/Configure/Storage/__tests__/buildStorageEntries.test.ts
  frontend/src/old-pages/Configure/Storage/__tests__/mapStorageToUiSettings.test.ts
  frontend/src/old-pages/Configure/Storage/buildStorageEntries.ts
  frontend/src/old-pages/Configure/Storage/storage.mapper.ts
Labels: release:feature

#63 Fixed broken 'delete stack' due to EcrPrivateRepository being not empty
  infrastructure/parallelcluster-ui.yaml
Labels: release:bugfix

#62 Adjust FSx settings layout
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Storage.tsx
Labels: release:improvement
