Repository aws/aws-parallelcluster-ui, pull requests merged in 2023-05, with the labels that each got.

#208 Support PC API 3.6.0 cloudformation template
  infrastructure/parallelcluster-ui.yaml
Labels: release:improvement

#221 Enable Cost Monitoring starting from PC 3.2.0
  frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
  frontend/src/feature-flags/featureFlagsProvider.ts
  frontend/src/old-pages/Clusters/Costs/__tests__/EnableCostMonitoringButton.test.tsx
  frontend/src/old-pages/Clusters/Costs/__tests__/useCostMonitoringStatus.test.tsx
Labels: release:feature

#234 Bump requests from 2.28.1 to 2.31.0
  requirements.in
  requirements.txt
Labels: dependencies
