Repository aws/aws-parallelcluster-ui, pull requests merged in 2023-03, with the labels that each got.

#82 Provide a reasonable default for table page size
  frontend/src/old-pages/Clusters/Accounting.tsx
  frontend/src/old-pages/Clusters/Clusters.tsx
  frontend/src/old-pages/Clusters/Filesystems.tsx
  frontend/src/old-pages/Clusters/Instances.tsx
  frontend/src/old-pages/Clusters/Scheduling.tsx
  frontend/src/old-pages/Images/CustomImages/CustomImageDetails.tsx
  frontend/src/old-pages/Images/CustomImages/CustomImages.tsx
  frontend/src/old-pages/Images/OfficialImages/OfficialImages.tsx
  frontend/src/old-pages/Users/Users.tsx
  frontend/src/shared/__tests__/extendCollectionsOptions.test.ts
  frontend/src/shared/extendCollectionsOptions.ts
Labels: release:improvement

#92 Move cluster name field from Source to Cluster section
  e2e/specs/wizard.spec.ts
  e2e/specs/wizard.template.spec.ts
  frontend/locales/en/strings.json
  frontend/src/old-pages/Configure/Cluster.tsx
  frontend/src/old-pages/Configure/Cluster/ClusterNameField.tsx
  frontend/src/old-pages/Configure/Cluster/__tests__/clusterName.validators.test.ts
  frontend/src/old-pages/Configure/Cluster/clusterName.validators.ts
  frontend/src/old-pages/Configure/Source.tsx
Labels: release:feature

#91 Added clusters actions in button group
  frontend/locales/en/strings.json
  frontend/src/old-pages/Clusters/Actions.tsx
Labels: release:improvement

#94 Select method to create cluster via button dropdown
  e2e/specs/wizard.spec.ts
  e2e/specs/wizard.template.spec.ts
  frontend/src/old-pages/Clusters/Actions.tsx
  frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx
  frontend/src/old-pages/Configure/Cluster.tsx
  frontend/src/old-pages/Configure/Cluster/ClusterNameField.tsx
  frontend/src/old-pages/Configure/Cluster/__tests__/ClusterNameField.test.tsx
  frontend/src/old-pages/Configure/Configure.tsx
  frontend/src/old-pages/Configure/useWizardNavigation.ts
Labels: release:feature

#103 Custom actions editor layout changes
  frontend/locales/en/strings.json
  frontend/src/css-properties.d.ts
  frontend/src/old-pages/Configure/Components.module.css
  frontend/src/old-pages/Configure/Components.tsx
  frontend/src/old-pages/Configure/__tests__/Components.test.tsx
Labels: release:improvement

#101 IMDS secured set as True by default for new cluster creation
  frontend/src/old-pages/Configure/HeadNode.tsx
  frontend/src/old-pages/Configure/__tests__/IMDSSecuredSettings.test.tsx
Labels: release:improvement

#107 Disable Actions dropdown if no actions inside of it is enabled
  frontend/src/old-pages/Clusters/Actions.tsx
Labels: release:improvement

#120 Don't act on IMDS secured default settings when in update mode
  frontend/src/old-pages/Configure/HeadNode.tsx
  frontend/src/old-pages/Configure/__tests__/IMDSSecuredSettings.test.tsx
Labels: release:bugfix

#135 Show count of total entries in table headers
  frontend/src/old-pages/Clusters/Clusters.tsx
  frontend/src/old-pages/Images/CustomImages/CustomImages.tsx
  frontend/src/old-pages/Images/OfficialImages/OfficialImages.tsx
  frontend/src/old-pages/Logs/LogMessagesTable.tsx
  frontend/src/old-pages/Logs/LogStreamsTable.tsx
Labels: release:improvement
